name: Build Tweak

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y make curl git perl unzip xz-utils dpkg-dev

    - name: Install Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos

    - name: Install Ellekit Toolchain
      run: |
        mkdir -p $HOME/toolchain
        curl -L https://github.com/ellekit/toolchain/releases/latest/download/ios-arm64e-clang-toolchain.tar.xz -o tc.tar.xz
        tar -xJf tc.tar.xz -C $HOME/toolchain
        echo "export PATH=$HOME/toolchain/usr/bin:$PATH" >> $GITHUB_ENV

    - name: Install iOS SDK (15.6)
      run: |
        mkdir -p $HOME/theos/sdks
        curl -L https://github.com/theos/sdks/releases/download/master-146e41f/iPhoneOS15.6.sdk.tar.xz -o sdk.tar.xz
        tar -xJf sdk.tar.xz -C $HOME/theos/sdks
        ls $HOME/theos/sdks

    - name: Build Tweak
      env:
        THEOS: $HOME/theos
      run: |
        export PATH=$HOME/toolchain/usr/bin:$PATH
        make clean
        make package FINALPACKAGE=1

    - name: Upload .deb
      uses: actions/upload-artifact@v4
      with:
        name: tweak
        path: packages/*.deb
